Neos:
  Neos:
    fusion:
      autoInclude:
        "Sandstorm.CookiePunch": true
  Fusion:
    defaultContext:
      "CookiePunch": Sandstorm\CookiePunch\Eel\Helper\CookiePunch
      "CookiePunchConfig": Sandstorm\CookiePunch\Eel\Helper\CookiePunchConfig

Sandstorm:
  CookiePunch:
    consent:
      privacyPolicyUrl: /privacy
      storageMethod: cookie
      cookieName: cookie_punch
      cookieExpiresAfterDays: 120
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      default: false
    groups:
      default:
        title: Sandstorm.CookiePunch:Groups:default.title
        description: Sandstorm.CookiePunch:Groups:default.description
        consent:
          default: true
    purposes:
      analytics: Analytics
    elements:
      block: true
      group: default
      options:
        message: Sandstorm.CookiePunch:Elements:options.message

