Neos:
  Neos:
    fusion:
      autoInclude:
        "Sandstorm.CookieCutter": true
  Fusion:
    defaultContext:
      "CookieCutter": Sandstorm\CookieCutter\Eel\Helper\CookieCutter
      "CookieCutterConfig": Sandstorm\CookieCutter\Eel\Helper\CookieCutterConfig

Sandstorm:
  CookieCutter:
    consent:
      privacyPolicyUrl: /privacy
      storageMethod: cookie
      cookieName: cookie_cutter
      cookieExpiresAfterDays: 120
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      default: false
    groups:
      default:
        title: Sandstorm.CookieCutter:Groups:default.title
        description: Sandstorm.CookieCutter:Groups:default.description
    purposes:
      analytics: Analytics
    elements:
      block: true
      group: default
      options:
        message: Sandstorm.CookieCutter:Elements:options.message
