Neos:
  Neos:
    fusion:
      autoInclude:
        "Sandstorm.CookiePunch": true
  Fusion:
    defaultContext:
      "CookiePunch": Sandstorm\CookiePunch\Eel\Helper\CookiePunch
      "CookiePunchConfig": Sandstorm\CookiePunch\Eel\Helper\CookiePunchConfig

Sandstorm:
  CookiePunch:
    consent:
      privacyPolicyUrl: /privacy
      elementID: "klaro"
      noAutoLoad: false
      htmlTexts: false
      embedded: false
      groupByPurpose: true
      storageMethod: cookie
      cookieName: cookie_punch
      cookieExpiresAfterDays: 120
      default: false
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      hideLearnMore: false
      noticeAsModal: false
      disablePoweredBy: false
      additionalClass: ~
    blocking:
      tagPatterns:
        script:
          "*":
            block: true
        iframe:
          "*":
            block: true
